pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                input message: 'Lanjutkan Ke tahap Deploy? (Klik "Proceed" untuk lanjut)'
                sh './jenkins/scripts/deliver.sh'
                sleep(time:1,unit:"MINUTES")
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
